Feature-17
CozyWool/Quizzify pull request #13
Opened 2024-03-25 18:12 UTC by Mirovinkin

Добавил команды

2024-03-25 18:20 UTC, CozyWool requested changes
Посмотрел, комменты оставил, как поправишь - запроси ревью еще раз

2024-03-25 18:20 UTC, CozyWool commented on Commands/Commands.cs
У меня вот такой код команды, он без raise метода:

```
public abstract class Command : ICommand
{
    public event EventHandler? CanExecuteChanged
    {
        add => CommandManager.RequerySuggested += value;
        remove => CommandManager.RequerySuggested -= value;
    }

    public bool CanExecute(object parameter)
    {
        return CanExecuteCmd(parameter);
    }

    public void Execute(object parameter)
    {
        ExecuteCmd(parameter);
    }

    protected virtual bool CanExecuteCmd(object parameter)
    {
        return true;
    }

    protected abstract void ExecuteCmd(object parameter);
}
```

2024-03-25 18:20 UTC, CozyWool commented on Commands/DelegateCommand.cs
также я бы добавил DefaultCanExecute как просто true
```
    private static readonly Func<object, bool> DefaultCanExecute = _ => true;

    public DelegateCommand(Action<object> executeAction) : this(executeAction, DefaultCanExecute)
    {
    }

```

2024-03-25 18:20 UTC, CozyWool commented on Commands/DelegateCommand.cs
А еще, как насчёт generic-версий команд? Можно конечно оставить и такие

2024-03-25 18:24 UTC, CozyWool commented on Commands/DelegateCommand.cs
> +namespace Command_
Что за namespace Command_? ты сделал как отдельную библиотеку или как?
Перенеси наверное лучше в сам проект и поправь namespace'ы

2024-03-25 18:26 UTC, Mirovinkin commented on Commands/DelegateCommand.cs
> +namespace Command_
Я пока не очень хорошо понимаю github, как и куда переносить. Завтра желательно созвониться или когда удобно, чтобы с этим разобраться.

2024-03-25 18:30 UTC, CozyWool commented on Commands/DelegateCommand.cs
> +namespace Command_
Не, я про то, что команды должны внутри solution лежать, с гитом все ок ты сделал

2024-03-25 18:32 UTC, Mirovinkin commented on Commands/DelegateCommand.cs
> +namespace Command_
Не совсем, насолько я знаю, можно без этого, у меня и так работает, так даже корректнее выглядит на мой взгляд

2024-03-25 18:32 UTC, CozyWool commented on Commands/DelegateCommand.cs
> +namespace Command_
А как оно видит их? Папка же вне папки проекта
Интересно, завтра протестирую

2024-03-25 18:34 UTC, Mirovinkin commented on Commands/DelegateCommand.cs
> +namespace Command_
![Screenshot 2024-03-25 233350](https://github.com/CozyWool/Quizzify/assets/137717625/cc348eb8-2036-4364-abcc-249ccf65cd69)
В этом проекте работало

2024-03-25 18:35 UTC, CozyWool commented on Commands/DelegateCommand.cs
> +namespace Command_
Так у тебя тут внутри папки проекта лежит, в общем ладно, завтра проверим

2024-03-25 18:35 UTC, Mirovinkin commented on Commands/DelegateCommand.cs
> +namespace Command_
Хорошо

2024-03-27 10:08 UTC, thisfozz commented
![](https://github.trello.services/images/mini-trello-icon.png) [QF. Implement Pattern «Command» (feature-17)](https://trello.com/c/169yd5ia/26-qf-implement-pattern-command-feature-17)

2024-03-28 17:23 UTC, closed without merging