Feature 23
CozyWool/Quizzify pull request #22
Opened 2024-03-29 09:55 UTC by DmitriyYakubovskiy

2024-03-29 10:20 UTC, thisfozz commented on Quizzify/Quizzify.Client/ViewModel/RegistrationViewModel.cs
>      }
Может все таки оставить заполнение newUser  на клиенте, а потом уже в конце делать отправку на сервер
`    private void RegistrationUser(object obj)
    {
        var aes = new AESManager();
        Guid guid = Guid.NewGuid();

        byte[] saltBytes = guid.ToByteArray();
        string salt = Convert.ToBase64String(saltBytes);

        string encryptedPassword = aes.Encrypt(UserPassword, salt);

        var newUser = new RegistrationModel()
        {
            UserId = guid,
            Login = UserLogin,
            Password = encryptedPassword,
            Email = UserEmail,
            SelectedSecretQuestionId = UserSelectedSecretQuestionId,
            SecretAnswer = UserSecretAnswer
        };

        // Отправляем  newUser на сервер
    }`

2024-03-29 13:52 UTC, thisfozz requested changes, later dismissed
Отписал в дм дискорда насчет метода LoginVerification

2024-03-29 13:52 UTC, thisfozz commented on Quizzify/Quizzify.MainServer/Hubs/MainHub.cs
> +        private bool RegistrationVerification(string userLogin, string userPassword, string userEmail, int userSelectedSecretQuestionId, string userSecretAnswer)
А тут ждать newUser, который добавляешь через контекст

2024-03-29 13:52 UTC, thisfozz commented on Quizzify/Quizzify.Client/ViewModel/AuthorizationViewModel.cs
> +    private async void RegistrationUser(object obj)
Разве метод "RegistrationUser" должен называться в авторизации?

2024-03-29 13:52 UTC, thisfozz commented on Quizzify/Quizzify.MainServer/Hubs/MainHub.cs
> +                    if (user.PasswordHash == userPassword) return true;//Тут наверное надо как расшифровывать
Вызови просто метод Decrypt отдав ему PasswordHash с БД

2024-03-29 15:01 UTC, thisfozz commented
![](https://github.trello.services/images/mini-trello-icon.png) [QF. Authorization User (feature-23)](https://trello.com/c/OK6TpUtz/39-qf-authorization-user-feature-23)

2024-03-30 06:00 UTC, lexeg commented on Quizzify/Quizzify.Client.Host/ClientHostHub.cs
> +using AutoMapper;
Я бы предложил рассмотреть такой вариант с авторизацией/регистрацией пользователя. Создать контроллер с двумя POST эндпоинтами. Один для входа пользователя, второй для регистрации.
![image](https://github.com/CozyWool/Quizzify/assets/4533553/0ce25cb8-7db0-4f73-97f1-c32dd1ba0d22)

Как написано про SignalR: 
> SignalR is a free and open-source software library for Microsoft ASP.NET that allows server code to send asynchronous notifications to client-side web applications. 

То есть это библиотека для оповещения других клиентов о чем-либо. Как я понимаю, при аутентификации или регистрации пользователя в вашем проекте оповещать никого не надо. Пользователь только производит операцию входа и еще не вступает в игру. А вот когда пользователь у вас по выданному коду будет входить в одну из викторин, вот тогда должен вступать SignalR в действие.
Подумайте над этим командно.

2024-03-30 06:00 UTC, lexeg commented on Quizzify/Quizzify.Client.Host/ClientHostHub.cs
> +        var config = new MapperConfiguration(cfg => cfg.AddProfile<MappingPlayer>());
Автомапперы, классы с бизнес-логикой, репозитории и пр. нет необходимости инициализировать в конструкторе, если есть DI-контейнер. Это можно поручить спокойно ему. Например, так:
![image](https://github.com/CozyWool/Quizzify/assets/4533553/77b3c7ba-075f-4685-84db-df90490745a4)

Можно подглядывать сюда: https://github.com/lexeg/ToDoService/tree/main/ToDoService.

И вот еще патч с небольшим примером кода: [0001-.patch](https://github.com/CozyWool/Quizzify/files/14810660/0001-.patch)

2024-04-03 18:07 UTC, CozyWool approved these changes
временный слив ветки в мейн, потом доделать необходимо

2024-04-03 18:07 UTC, merged